name: jarvis
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
    - openai>=1.97.0
    - numpy>=1.24.0
    - pandas>=2.0.0
    - flask>=2.3.0
    - flask-socketio>=5.3.0
    - python-socketio>=5.8.0
    - requests>=2.31.0
    - psutil>=5.9.0
    - python-dotenv>=1.0.0
    - nltk>=3.8.0
    - textblob>=0.17.0
    - beautifulsoup4>=4.12.0
    - newsapi-python>=0.2.6
    - python-dateutil>=2.8.0
    - pytz>=2023.3
    - schedule>=1.2.0
    - click>=8.1.0
    - rich>=13.0.0
    - colorama>=0.4.6
    - pyyaml>=6.0
    - SpeechRecognition>=3.10.0
    - pyttsx3>=2.90
    - pyaudio>=0.2.11 